name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet tool install -g dotnet-format --version 4.1.131201
    - uses: pre-commit/action@v2.0.0
